# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 615)
        MainWindow.setStyleSheet("background-color:black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.screen = QtWidgets.QLabel(self.centralwidget)
        self.screen.setGeometry(QtCore.QRect(0, 0, 881, 621))
        font = QtGui.QFont()
        font.setFamily("Anurati")
        font.setPointSize(16)
        self.screen.setFont(font)
        self.screen.setText("")
        self.screen.setPixmap(QtGui.QPixmap("res/HomeScreenDark.gif"))
        self.screen.setScaledContents(True)
        self.screen.setObjectName("screen")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 881, 41))
        self.frame.setStyleSheet("background-color:rgb(48,48,48);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Close = QtWidgets.QPushButton(self.frame)
        self.Close.setGeometry(QtCore.QRect(824, 0, 51, 41))
        self.Close.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(175,0,0);\n"
"    border:none;\n"
"}\n"
"")
        self.Close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/Close X.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close.setIcon(icon)
        self.Close.setObjectName("Close")
        self.Minimize = QtWidgets.QPushButton(self.frame)
        self.Minimize.setGeometry(QtCore.QRect(770, 0, 51, 41))
        self.Minimize.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(175,0,0);\n"
"    border:none;\n"
"}\n"
"")
        self.Minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/Minimize Centered.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Minimize.setIcon(icon1)
        self.Minimize.setObjectName("Minimize")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 281, 21))
        self.label.setStyleSheet("color:white;\n"
"font-size:15px;")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 510, 75, 23))
        self.pushButton_3.setStyleSheet("\n"
"QPushButton{\n"
"    background-color:white;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:gray;\n"
"    color:white;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.TASK = QtWidgets.QLineEdit(self.centralwidget)
        self.TASK.setGeometry(QtCore.QRect(570, 60, 201, 21))
        self.TASK.setStyleSheet("background-color:white;\n"
"color:black;")
        self.TASK.setObjectName("TASK")
        self.TakeTASK = QtWidgets.QPushButton(self.centralwidget)
        self.TakeTASK.setGeometry(QtCore.QRect(770, 60, 75, 23))
        self.TakeTASK.setStyleSheet("\n"
"QPushButton{\n"
"    background-color:white;\n"
"    border:1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:gray;\n"
"    color:white;\n"
"}")
        self.TakeTASK.setObjectName("TakeTASK")
        self.VoiceGIF = QtWidgets.QLabel(self.centralwidget)
        self.VoiceGIF.setGeometry(QtCore.QRect(10, 470, 141, 111))
        self.VoiceGIF.setStyleSheet("background-color:transparent;\n"
"")
        self.VoiceGIF.setText("")
        self.VoiceGIF.setScaledContents(True)
        self.VoiceGIF.setObjectName("VoiceGIF")
        self.reply = QtWidgets.QLabel(self.centralwidget)
        self.reply.setGeometry(QtCore.QRect(210, 520, 621, 51))
        self.reply.setStyleSheet("color:white;\n"
"background-color:transparent;\n"
"font-size:20px;\n"
"")
        self.reply.setText("")
        self.reply.setObjectName("reply")
        self.DateL = QtWidgets.QLabel(self.centralwidget)
        self.DateL.setGeometry(QtCore.QRect(140, 70, 221, 41))
        font = QtGui.QFont()
        font.setFamily("DS-Digital")
        font.setPointSize(1)
        self.DateL.setFont(font)
        self.DateL.setStyleSheet("background-color:transparent;\n"
"border:none;\n"
"color:rgb(53,184,240);\n"
"font-size:20px;")
        self.DateL.setText("")
        self.DateL.setObjectName("DateL")
        self.TimeL = QtWidgets.QLabel(self.centralwidget)
        self.TimeL.setGeometry(QtCore.QRect(30, 70, 121, 41))
        font = QtGui.QFont()
        font.setFamily("DS-Digital")
        font.setPointSize(1)
        self.TimeL.setFont(font)
        self.TimeL.setStyleSheet("background-color:transparent;\n"
"border:none;\n"
"color:rgb(53,184,240);\n"
"font-size:20px;")
        self.TimeL.setText("")
        self.TimeL.setObjectName("TimeL")
        self.time_Date_frame = QtWidgets.QLabel(self.centralwidget)
        self.time_Date_frame.setGeometry(QtCore.QRect(0, 60, 311, 71))
        self.time_Date_frame.setStyleSheet("background-color:transparent;")
        self.time_Date_frame.setText("")
        self.time_Date_frame.setScaledContents(False)
        self.time_Date_frame.setObjectName("time_Date_frame")
        self.framep = QtWidgets.QLabel(self.centralwidget)
        self.framep.setGeometry(QtCore.QRect(130, 70, 5, 50))
        self.framep.setStyleSheet("background-color:transparent;")
        self.framep.setText("")
        self.framep.setObjectName("framep")
        self.info = QtWidgets.QLabel(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(680, 220, 191, 291))
        self.info.setStyleSheet("background-color:transparent;")
        self.info.setText("")
        self.info.setObjectName("info")
        self.CPU = QtWidgets.QLabel(self.centralwidget)
        self.CPU.setGeometry(QtCore.QRect(710, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("DS-Digital")
        font.setPointSize(1)
        self.CPU.setFont(font)
        self.CPU.setStyleSheet("background-color:transparent;\n"
"border:none;\n"
"color:transparent;\n"
"font-size:20px;\n"
"")
        self.CPU.setObjectName("CPU")
        self.RAM = QtWidgets.QLabel(self.centralwidget)
        self.RAM.setGeometry(QtCore.QRect(710, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily("DS-Digital")
        font.setPointSize(1)
        self.RAM.setFont(font)
        self.RAM.setStyleSheet("background-color:transparent;\n"
"border:none;\n"
"color:transparent;\n"
"font-size:20px;\n"
"")
        self.RAM.setObjectName("RAM")
        self.Battery = QtWidgets.QLabel(self.centralwidget)
        self.Battery.setGeometry(QtCore.QRect(710, 380, 121, 31))
        font = QtGui.QFont()
        font.setFamily("DS-Digital")
        font.setPointSize(1)
        self.Battery.setFont(font)
        self.Battery.setStyleSheet("background-color:transparent;\n"
"border:none;\n"
"color:transparent;\n"
"font-size:20px;\n"
"")
        self.Battery.setObjectName("Battery")
        self.screen.raise_()
        self.frame.raise_()
        self.pushButton_3.raise_()
        self.TASK.raise_()
        self.TakeTASK.raise_()
        self.VoiceGIF.raise_()
        self.reply.raise_()
        self.time_Date_frame.raise_()
        self.DateL.raise_()
        self.TimeL.raise_()
        self.framep.raise_()
        self.info.raise_()
        self.CPU.raise_()
        self.RAM.raise_()
        self.Battery.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "M.E.R.R.Y:Meet With The Real Future"))
        self.pushButton_3.setText(_translate("MainWindow", "Start"))
        self.TakeTASK.setText(_translate("MainWindow", "Enter"))
        self.CPU.setText(_translate("MainWindow", "C.P.U:100%"))
        self.RAM.setText(_translate("MainWindow", "R.A.M:100%"))
        self.Battery.setText(_translate("MainWindow", "BATTERY:100%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
