# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(510, 350)
        MainWindow.setStyleSheet("background-color:rgb(68,68,68);\n"
"color:white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loginLabel = QtWidgets.QLabel(self.centralwidget)
        self.loginLabel.setGeometry(QtCore.QRect(150, 40, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Anurati")
        font.setPointSize(1)
        self.loginLabel.setFont(font)
        self.loginLabel.setStyleSheet("color:white;\n"
"font-size:25px;\n"
"background-color:transparent;")
        self.loginLabel.setObjectName("loginLabel")
        self.screen = QtWidgets.QLabel(self.centralwidget)
        self.screen.setGeometry(QtCore.QRect(-4, -9, 521, 361))
        self.screen.setText("")
        self.screen.setPixmap(QtGui.QPixmap("bg.gif"))
        self.screen.setScaledContents(True)
        self.screen.setObjectName("screen")
        self.Close = QtWidgets.QPushButton(self.centralwidget)
        self.Close.setGeometry(QtCore.QRect(460, 0, 51, 41))
        self.Close.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color:rgb(48,48,48);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(175,0,0);\n"
"    border:none;\n"
"}\n"
"")
        self.Close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/Close X.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Close.setIcon(icon)
        self.Close.setObjectName("Close")
        self.Min = QtWidgets.QPushButton(self.centralwidget)
        self.Min.setGeometry(QtCore.QRect(410, 0, 51, 41))
        self.Min.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color:rgb(48,48,48);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(175,0,0);\n"
"    border:none;\n"
"}\n"
"")
        self.Min.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("res/Minimize Centered.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Min.setIcon(icon1)
        self.Min.setObjectName("Min")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 411, 41))
        self.frame.setStyleSheet("background-color:rgb(48,48,48);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 5, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 120, 71, 31))
        self.label_2.setStyleSheet("background-color:transparent;\n"
"font-size:15px;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 111, 31))
        self.label_3.setStyleSheet("background-color:transparent;\n"
"font-size:15px;")
        self.label_3.setObjectName("label_3")
        self.UsernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.UsernameInput.setGeometry(QtCore.QRect(140, 120, 231, 31))
        self.UsernameInput.setStyleSheet("border-radius:10px;\n"
"border:2px solid white;\n"
"color:white;")
        self.UsernameInput.setObjectName("UsernameInput")
        self.MusicDirInput = QtWidgets.QLineEdit(self.centralwidget)
        self.MusicDirInput.setGeometry(QtCore.QRect(140, 170, 231, 31))
        self.MusicDirInput.setStyleSheet("border-radius:10px;\n"
"border:2px solid white;\n"
"color:white;")
        self.MusicDirInput.setObjectName("MusicDirInput")
        self.LoginB = QtWidgets.QPushButton(self.centralwidget)
        self.LoginB.setGeometry(QtCore.QRect(200, 250, 75, 23))
        self.LoginB.setStyleSheet("\n"
"QPushButton{\n"
"    background-color:white;\n"
"    border-radius:10px;\n"
"    color:black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:gray;\n"
"    color:white;\n"
"}")
        self.LoginB.setObjectName("LoginB")
        self.BrowseB = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseB.setGeometry(QtCore.QRect(380, 175, 75, 23))
        self.BrowseB.setStyleSheet("\n"
"QPushButton{\n"
"    background-color:white;\n"
"    color:black;\n"
"    border:1px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:gray;\n"
"    color:white;\n"
"}")
        self.BrowseB.setObjectName("BrowseB")
        self.screen.raise_()
        self.loginLabel.raise_()
        self.Close.raise_()
        self.Min.raise_()
        self.frame.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.UsernameInput.raise_()
        self.MusicDirInput.raise_()
        self.LoginB.raise_()
        self.BrowseB.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginLabel.setText(_translate("MainWindow", "Login To the Future"))
        self.label.setText(_translate("MainWindow", "M.E.R.R.Y:Meet With The Real Future"))
        self.label_2.setText(_translate("MainWindow", "Username:"))
        self.label_3.setText(_translate("MainWindow", "Music Directory:"))
        self.LoginB.setText(_translate("MainWindow", "Login"))
        self.BrowseB.setText(_translate("MainWindow", "Browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
